version: "3"

services:
  rest-dns-client:
    build:
      context: .
    container_name: rest-dns-client
    volumes:
      - /etc/hosts:/opt/src/hosts
    environment:
      - API_URL=${API_URL}
    restart: unless-stopped
